name: Terraform Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    name: Terraform Validate & Format
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1

      # Init (required before validate)
      - name: Terraform Init
        run: terraform init -backend=false

      # Check formatting
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # Validate configuration
      - name: Terraform Validate
        run: terraform validate
